name: "Build and Publish Python Packages"

on:
  push:
    tags: "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  build_sdist:

    name: "Source distribution"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: "Build source distribution"
        run: |
          python setup.py sdist

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: yoga-sdist
          path: dist/
          retention-days: 1

  build_wheel_linux_i686:

    strategy:
      matrix:
        python-version: [cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310]

    name: "Wheel for ${{ matrix.python-version }} manylinux2010 i686"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Build Python Wheel for Linux (manylinux2010_i686)"
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_i686
        with:
          python-versions: ${{ matrix.python-version }}
          build-requirements: cffi>=1.0.0

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: yoga-wheel-linux
          path: dist/*manylinux*.whl
          retention-days: 1

  build_wheel_linux_x86_64:

    strategy:
      matrix:
        python-version: [cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310]

    name: "Wheel for ${{ matrix.python-version }} manylinux2010 x86_64"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Build Python Wheel for Linux (manylinux2010_x86_64)"
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
        with:
          python-versions: ${{ matrix.python-version }}
          build-requirements: cffi>=1.0.0

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: yoga-wheel-linux
          path: dist/*manylinux*.whl
          retention-days: 1

  build_wheel_windows_x86_64:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    name: "Wheel for py${{ matrix.python-version }} win amd64"
    runs-on: windows-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Python dependencies"
        run: |
          pip install wheel

      - name: "Build Python Wheel"
        run: |
          python setup.py bdist_wheel

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: yoga-wheel-windows
          path: dist/
          retention-days: 1

  build_wheel_macos_x86_64:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        macos-version: ["10.15"]

    name: "Wheel for py${{ matrix.python-version }} macos-${{ matrix.macos-version }} intel"
    runs-on: macos-${{ matrix.macos-version }}

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Python dependencies"
        run: |
          pip install wheel

      - name: "Build Python Wheel"
        run: |
          python setup.py bdist_wheel

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: yoga-wheel-macos
          path: dist/
          retention-days: 1

  publish_pypi:

    name: "Publish packages on PyPI"
    runs-on: ubuntu-latest
    needs:
      - build_sdist
      - build_wheel_linux_i686
      - build_wheel_linux_x86_64
      - build_wheel_windows_x86_64
      - build_wheel_macos_x86_64

    steps:

      - name: "Download artifacts"
        uses: actions/download-artifact@v2

      - name: "Move packages to the dist/ folder"
        run: |
          mkdir dist/
          mv yoga-sdist/* dist/
          mv yoga-wheel-*/*.whl dist/

      - name: "Publish packages on PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
